language: node_js
node_js:
  - "iojs"
  - "iojs-v1.0.4" 
addons:
  code_climate:
    repo_token: 8cdf2574b11c9111aeb7da0578fec0e637eb0cf19cf740dcd23e4992cc8c992d
script: "npm run coverage"
after_script:
  - codeclimate < etc/lcov.info